# Waypoints Plugin by Croissant Bridge (+ Aelithron) on the Not-yet-named Server.

# Prefix
# This will appear in front of all messages by the plugin.
# You can use color codes here! Guide: https://wiki.ess3.net/mc
Prefix: "&8[&bWaypoints&8]"